### ISSUE TITLE
Not work

### ISSUE THREAD

**Issue by Neinndall** [autergame/MindCorpViewer-Rust#1]
```
Reading config json file
Finished reading config json file
thread 'main' panicked at 'Expected string in DdsPath PATHS', src\config_json.rs:90:18
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```

the last version 1.0.0, does not contain the executable .exe and what config file must i have in the folder?

Edit: You should add the possibility of PUTTING the hashes manually, I mean, the user, because I have more updated hashes than CDTB.

**Comment by fernpi** [comment]
I added the windows version: https://github.com/autergame/MindCorpViewer-Rust/releases/download/v1.0.0/mindcorpviewer-rust_windows.exe

**Comment by fernpi** [comment]
And the new version 1.0.0 have breaking changes in config.json, you will need to download files.zip and extract to same folder of mindcorpviewer-rust_windows.exe and follow the rules of config.json in [readme](https://github.com/autergame/MindCorpViewer-Rust/blob/main/README.md)

**Comment by Neinndall** [comment]
Ok! I ll test.

PD: note what I mentioned:
You should add the possibility of PUTTING the hashes manually, I mean, the user, because I have more updated hashes than CDTB, this will be cool :)

THX!

**Comment by fernpi** [comment]
MindCorpViewer-Rust does not use hashes, this one uses [BinReader-Rust](https://github.com/autergame/BinReader-Rust)

**Comment by Neinndall** [comment]
Ok, now work! 

How can I export the model along with its textures, animations to the glTF?

**Comment by fernpi** [comment]
Yes in export tab inside each model, you can choose between glb and gltf, i recommend using gltf for blender, and glb for others web viewers tools

**Comment by Neinndall** [comment]
ok! thx! Ill test the tool! any bugs ill report it, thx so much!

**Comment by fernpi** [comment]
If everything is working correctly please close the issue or send a message so i can close
