### ISSUE TITLE
[Suggestion and Bug] Saving user settings, not deleting the selected champion and CRASH with SETT SPIRIT BLOSSOM and maybe others...

### ISSUE THREAD

**Issue by Neinndall** [autergame/MindCorpViewer-Rust#2]
![image](https://user-images.githubusercontent.com/66384195/192252686-0b878cfc-97d4-414d-a857-04bf0b132797.png)

1.- When you click "delete item" the program closes automatically and does not delete the selected item. With my preview config.json

2.- to add the skin of sett spirit blossom, crashed the program.

3.- Every time I open the program I have to give it to synchronize so that it does not exceed the FPS, could you add that the settings are saved? And you don't have to select it every time you open the program!

Thank you very much!

**Comment by fernpi** [comment]
Can you send your config and the sett skin please?

**Comment by fernpi** [comment]
Synchronized is bind to first model, please use for combined animations for example: xayah and rakan. And please disable when not using.

**Comment by Neinndall** [comment]
here the config of sett spirit blossom
![image](https://user-images.githubusercontent.com/66384195/192502818-d1fe26fb-9a43-43e4-b82b-fe371eaa1204.png)

I add it from here and crash

**Comment by fernpi** [comment]
I need the files of this sett skin, so i can reproduce the bug.

**Comment by Neinndall** [comment]
I add: I have tried several models, and it seems that the program does not put the models correctly.

![image](https://user-images.githubusercontent.com/66384195/192512527-82f7cc54-209d-454a-8b40-846e091fe6b2.png)

**Comment by Neinndall** [comment]
https://anonymfile.com/R6XK/sett.rar

here the files of sett

**Comment by fernpi** [comment]
> I add: I have tried several models, and it seems that the program does not put the models correctly.
> 
> ![image](https://user-images.githubusercontent.com/66384195/192512527-82f7cc54-209d-454a-8b40-846e091fe6b2.png)

This is normal, you have to set the texture for each mesh in Meshes tab. The program is not automatic.

**Comment by Neinndall** [comment]
Any ETA of Sett Spirit Blossom?

**Comment by fernpi** [comment]
![image](https://user-images.githubusercontent.com/24947356/192638888-49ddc387-0fb1-4ac5-adc7-f7dec65cb4d3.png)
Sett is working correctly.
My config: https://pastebin.com/xyqBiD64

**Comment by fernpi** [comment]
Remove button fixed: https://github.com/autergame/MindCorpViewer-Rust/releases/tag/v1.1.1

**Comment by Neinndall** [comment]
I thought that the program was able to deduce or have a pattern to add the textures where they should be. Thx for u work! :)
