### ISSUE TITLE
About v1.2.1 - false positive virus detection

### ISSUE THREAD

**Issue by Neinndall** [autergame/MindCorpViewer-Rust#3]
It is rare that it is detected as a virus while the other versions have not had a problem.

I want to post it, to make sure everything is... okay.

**Comment by fernpi** [comment]
Which antivirus detected this false positive?

**Comment by Neinndall** [comment]
Windows Defender

**Comment by fernpi** [comment]
I can not do anything about it, the code is open source, anyway whoever is going to use the program can compile if they do not trust the releases.
