### ISSUE TITLE
Suggestion - Possibility of adding the option to export the model in PNG

### ISSUE THREAD

**Issue by Neinndall** [autergame/MindCorpViewer-Rust#4]
I explained. It is very easy to take a screenshot of the software and enough, but I put the idea that I have.

It arises from the Windows 3D Viewer, when you add a model it gives you the possibility of exporting the image with transparency (without background) and in the resolution you want, also the most important thing, exporting the image in JPG, PNG etc. ..
![image](https://user-images.githubusercontent.com/66384195/216989704-359831e9-1f14-46d5-9bd8-c563dc3ae676.png)

**Comment by fernpi** [comment]
Added: https://github.com/autergame/MindCorpViewer-Rust/releases/tag/v1.4.0
