### ISSUE TITLE
Crashed when put a turret model and dont show the models

### ISSUE THREAD

**Issue by Neinndall** [autergame/MindCorpViewer-Rust#5]
![image](https://user-images.githubusercontent.com/66384195/220797495-9ad5584e-fe82-4f8c-9fe7-3887a933cbd4.png)

Also, skin 28 is not shown, nor is skin 30.

**Comment by fernpi** [comment]
Send the files so i can debug

**Comment by Neinndall** [comment]
[turret.zip](https://github.com/autergame/MindCorpViewer-Rust/files/10813074/turret.zip)
I don't know if there will be more models that cannot be added or crashes, I had the opportunity to try this model and it failed!

**Comment by fernpi** [comment]
i cant believe that riot has made this way, the model is so tiny
![image](https://user-images.githubusercontent.com/24947356/221025201-64eb009e-f823-418b-8f90-58d7dedf7e1d.png)

**Comment by fernpi** [comment]
Maybe i will add a translation, rotation, scale option
